//
//  RecordsListWorker.swift
//  BnetApplication
//
//  Created by Артем Григорян on 12/08/2019.
//  Copyright (c) 2019 Artyom Grigoryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RecordsListService {
    private var records: [ResponseData2]?
    private var fetcherService: DataFetcherService!
    
    init() {
        fetcherService = DataFetcherService()
    }
    
    func getRecords(session: String, completion: @escaping (Response<[ResponseData2]>) -> Void) {
        fetcherService.getRecords(session: session) { [weak self] (response, error) in
            // Отсутствует интернет-соединение.
            if let error = error {
                completion(.failure(error.localizedDescription))
            // Другая ошибка, указанная в разделе "Примеры ошибок" на сайте https://bnet.i-partner.ru/testAPI/
            } else if response?.status == 0 {
                completion(.failure(response!.error!))
            // Отсутствие ошибок.
            } else {
                guard let self = self, let records = response?.data else { return }
                self.records = records.first
                completion(.success(self.records!))
            }
        }
    }
}
