//
//  RecordsListWorker.swift
//  BnetApplication
//
//  Created by Артем Григорян on 12/08/2019.
//  Copyright (c) 2019 Artyom Grigoryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RecordsListService {
    private var networking: Networking
    private var fetcher: DataFetcher
    private var records: [ResponseData2]?
    
    init() {
        networking = NetworkService()
        fetcher = NetworkDataFetcher(networking: networking)
    }
    
    func getRecords(session: String, completion: @escaping (Response<[ResponseData2]>) -> Void) {
        fetcher.getRecords(session: session) { [weak self] (response, error) in
            guard let self = self, let records = response?.data else {
                return completion(.failure(error!.localizedDescription))
            }
            self.records = records.first
            completion(.success(self.records!))
        }
    }
}
